services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    working_dir: /app
    restart: always
